In [ ]:
from google.colab import drive
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset = pd.read_csv('/Data_classification.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state=0)

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
logistic_regressor = LogisticRegression(random_state=0)
logistic_regressor.fit(X_train, y_train)

y_pred = logistic_regressor.predict(X_test)

c_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(c_matrix)
print("Accuracy Score:")
accuracy_score(y_test, y_pred)

Confusion Matrix:
[[103   4]
 [  5  59]]
Accuracy Score:


0.9473684210526315

In [ ]:
# K Nearest Neighbors

from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p=2)
knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)

c_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(c_matrix)
print("Accuracy Score:")
accuracy_score(y_test, y_pred)

Confusion Matrix:
[[103   4]
 [  5  59]]
Accuracy Score:


0.9473684210526315

In [ ]:
# Support Vector Machine

from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'linear', random_state = 0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

c_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(c_matrix)
print("Accuracy Score:")
accuracy_score(y_test, y_pred)

Confusion Matrix:
[[102   5]
 [  5  59]]
Accuracy Score:


0.9415204678362573

In [ ]:
# Kernel SVM

from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'sigmoid', random_state = 0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

c_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(c_matrix)
print("Accuracy Score:")
accuracy_score(y_test, y_pred)

Confusion Matrix:
[[102   5]
 [  3  61]]
Accuracy Score:


0.9532163742690059

In [ ]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_test)

c_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(c_matrix)
print("Accuracy Score:")
accuracy_score(y_test, y_pred)

Confusion Matrix:
[[103   4]
 [  3  61]]
Accuracy Score:


0.9590643274853801

In [ ]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier
rt_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rt_classifier.fit(X_train, y_train)

y_pred = rt_classifier.predict(X_test)

c_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(c_matrix)
print("Accuracy Score:")
accuracy_score(y_test, y_pred)

Confusion Matrix:
[[102   5]
 [  6  58]]
Accuracy Score:


0.935672514619883

In [ ]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB
naive_bayes_c = GaussianNB()
naive_bayes_c.fit(X_train, y_train)

y_pred = naive_bayes_c.predict(X_test)

c_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(c_matrix)
print("Accuracy Score:")
accuracy_score(y_test, y_pred)

Confusion Matrix:
[[99  8]
 [ 2 62]]
Accuracy Score:


0.9415204678362573